#!/bin/sh

set -e

. "$(dirname $0)/os_functions"

OS=$(os_name)
ARCH=$(os_arch)
PLATFORM=${1:-$OS/$ARCH}

docker buildx build . --platform=$PLATFORM --file ./docker/Dockerfile --target=output --output type=local,dest=./lib/$PLATFORM
git submodule status > ./lib/$PLATFORM/submodules.txt
