#!/bin/sh

set -e

os_name() {
  case $(uname) in
    Linux)
      echo linux
      ;;
    Darwin)
      echo darwin
    *)
      echo unknown
      ;;
  esac
}

os_arch() {
  case $(arch) in
    x86_64)
      echo amd64
      ;;
    aarch64)
      echo arm64
      ;;
    arm64)
      echo arm64
      ;;
    *)
      echo unknown
      ;;
  esac
}
