name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
      - run: pip install pipenv
      - run: pipenv sync --dev
      - run: pipenv run check
      - run: pipenv run lint
      - run: ./scripts/extract_libs
      - run: pipenv run test
      - run: pipenv run flit build
