name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  define-globals:
    runs-on: ubuntu-latest
    outputs:
      platforms: ${{ steps.matrix.outputs.platforms }}
      submodules: ${{ steps.submodules.outputs.platforms }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - id: matrix
        run: |
          echo 'platforms=["linux/amd64", "linux/arm64"]' >> "$GITHUB_OUTPUT"
      - id: submodules
        run: |
          echo "php-src=$(git submodule status ./php-src | awk '{ print $1 }')" >> "$GITHUB_OUTPUT"
          echo "phpy=$(git submodule status ./phpy | awk '{ print $1 }')" >> "$GITHUB_OUTPUT"
  prepare:
    needs: [define-globals]
    strategy:
      matrix:
        platform: ${{ fromJSON(needs.define-globals.outputs.platforms) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          target: build
          push: false
          platforms: ${{ matrix.platform }}
          cache-from: type=registry,ref=ghcr.io/wooseopkim/phpypy:cache-php-src-${{ needs.define-globals.outputs.submodules.php-src }}-phpy-${{ needs.define-globals.outputs.submodules.phpy }}
          cache-to: type=registry,ref=ghcr.io/wooseopkim/phpypy:cache-php-src-${{ needs.define-globals.outputs.submodules.php-src }}-phpy-${{ needs.define-globals.outputs.submodules.phpy }}
  check:
    # for Linux ARM runners are supported only as larger runners,
    # we need to run cross-platform tests inside Docker containers
    # see https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners
    runs-on: ubuntu-latest
    needs: [define-globals, prepare]
    strategy:
      matrix:
        platform: ${{ fromJSON(needs.define-globals.outputs.platforms) }}
    env:
      PLATFORM: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          target: run
          push: false
          load: true
          tags: phpypy
          platforms: ${{ matrix.platform }}
          cache-from: type=registry,ref=ghcr.io/wooseopkim/phpypy:cache-php-src-${{ needs.define-globals.outputs.submodules.php-src }}-phpy-${{ needs.define-globals.outputs.submodules.phpy }}
          cache-to: type=registry,ref=ghcr.io/wooseopkim/phpypy:cache-php-src-${{ needs.define-globals.outputs.submodules.php-src }}-phpy-${{ needs.define-globals.outputs.submodules.phpy }}

      - run: docker run --rm phpypy pipenv run test
      - run: docker run --rm phpypy pipenv run flit build
  build:
    runs-on: ubuntu-latest
    needs: [define-globals, prepare]
    strategy:
      matrix:
        platform: ${{ fromJSON(needs.define-globals.outputs.platforms) }}
    steps:
      - id: target-platform
        run: |
          SPLIT=(${PLATFORM//\// })
          echo "os=${SPLIT[0]}" >> $GITHUB_OUTPUT
          echo "arch=${SPLIT[1]}" >> $GITHUB_OUTPUT
        env:
          PLATFORM: ${{ matrix.platform }}

      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          target: run
          push: false
          outputs: type=local,dest=./lib/${{ steps.target-platform.outputs.os }}/${{ steps.target-platform.outputs.arch }}
          platforms: ${{ matrix.platform }}
          cache-from: type=registry,ref=ghcr.io/wooseopkim/phpypy:cache-php-src-${{ needs.define-globals.outputs.submodules.php-src }}-phpy-${{ needs.define-globals.outputs.submodules.phpy }}
          cache-to: type=registry,ref=ghcr.io/wooseopkim/phpypy:cache-php-src-${{ needs.define-globals.outputs.submodules.php-src }}-phpy-${{ needs.define-globals.outputs.submodules.phpy }}

      - if: github.ref == 'refs/heads/main'
        # currently v4 does not work with nektos/act - same for download-artifact
        # see https://github.com/nektos/act/issues/329
        uses: actions/upload-artifact@v3
        with:
          name: libs-${{ steps.target-platform.outputs.os }}-${{ steps.target-platform.outputs.arch }}
          path: ./lib
          if-no-files-found: error
  publish:
    if: github.ref == 'refs/heads/main'
    needs: [check, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install pipenv
      - run: pipenv sync --dev

      - uses: actions/download-artifact@v3
        with:
          path: /tmp/phpypy
          pattern: libs-*
      - run: mv /tmp/phpypy/libs-* ./lib

      - run: pipenv run flit publish
        env:
          FLIT_INDEX_URL: https://test.pypi.org/legacy/
          FLIT_USERNAME: __token__
          FLIT_PASSWORD: ${{ secrets.PYPI_TOKEN }}
