name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: pip install pipenv
      - uses: pipenv sync
      - uses: pipenv run check
      - uses: pipenv run lint
      - uses: pipenv run test
  build:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: pip install pipenv
      - uses: pipenv sync
      - uses: pipenv run flit build
