name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: pip install pipenv
      - run: pipenv sync --dev
      - run: pipenv run check
      - run: pipenv run lint
      - run: ./scripts/extract_libs '${{ matrix.platform }}'
      - run: pipenv run test
      - run: pipenv run flit build
